config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'
  resources :pizzas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :pizzaingredients
  has_many :pizzas, through: :pizzaingredients
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  has_many :pizzaitems
  has_many :pizzas, through: :pizzaitems
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_one :item
end

app/models/pizza.rb
class Pizza < ApplicationRecord
   has_many :sizes, dependent: :destroy
   has_many :pizzaitems
   has_many :items, through: :pizzaitems
   has_many :pizzaingredients
   has_many :ingredients, through: :pizzaingredients

   accepts_nested_attributes_for :sizes, reject_if: :all_blank, allow_destroy: true

   accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

end

app/models/pizzaingredient.rb
class Pizzaingredient < ApplicationRecord
  belongs_to :pizza
  belongs_to :ingredient
end

app/models/pizzaitem.rb
class Pizzaitem < ApplicationRecord
  belongs_to :item
  belongs_to :pizza
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :pizza
  enum :name, %i(large medium small)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: %i[ show edit update destroy ]

  # GET /pizzas or /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1 or /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas or /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to pizza_url(@pizza), notice: "Pizza was successfully created." }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1 or /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to pizza_url(@pizza), notice: "Pizza was successfully updated." }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1 or /pizzas/1.json
  def destroy
    @pizza.destroy!

    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: "Pizza was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pizza_params
      params.require(:pizza).permit(:name, sizes_attributes: [:id, :_destroy, :price, :name], ingredient_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pizzas/_form.html.erb
<%= form_with(model: pizza, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }) do |form| %>
  <% if pizza.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
        <% pizza.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <template data-nested-form-target="template">
    <%= form.fields_for :sizes, Size.new, child_index: 'NEW_RECORD' do |size_fields| %>
      <%= render "pizzas/size_form", form: size_fields %>
    <% end %>
  </template>

  <%= form.fields_for :sizes do |size_fields| %>
    <%= render "pizzas/size_form", form: size_fields %>
  <% end %>

  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add">Add size</button>

  <div>
  <%= form.label :ingredients%>
  <%= form.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
  <div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pizzas/_pizza.html.erb
<div id="<%= dom_id pizza %>">
  <p>
    <strong>Name:</strong>
    <%= pizza.name %>
  </p>

  <% if pizza.sizes.present? %>
    <%pizza.sizes.each do |size|%>

      <%= size.name%>
      <%=size.price%>
    <%end%>
  <%end%>

  <% if pizza.ingredients.present? %>
    <%pizza.ingredients.each do |ingredient|%>
      
      <%= ingredient.name%>
    <%end%>
  <%end%>

</div>

app/views/pizzas/_size_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= form.object.new_record? %>">
  <%= form.label :name %>
  <%= select_tag :status, options_for_select(Size.names) %>

  
  <%= form.label :price %>
  <%= form.number_field :price, step: 0.01, min: 0.0%>

  <button type="button" data-action="nested-form#remove">Remove todo</button>

  <%= form.hidden_field :_destroy %>
</div>

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<%= render "form", pizza: @pizza %>

<br>

<div>
  <%= link_to "Show this pizza", @pizza %> |
  <%= link_to "Back to pizzas", pizzas_path %>
</div>

app/views/pizzas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pizzas</h1>

<div id="pizzas">
  <% @pizzas.each do |pizza| %>
    <%= render pizza %>
    <p>
      <%= link_to "Show this pizza", pizza %>
    </p>
  <% end %>
</div>

<%= link_to "New pizza", new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<%= render "form", pizza: @pizza %>

<br>

<div>
  <%= link_to "Back to pizzas", pizzas_path %>
</div>

app/views/pizzas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pizza %>

<div>
  <%= link_to "Edit this pizza", edit_pizza_path(@pizza) %> |
  <%= link_to "Back to pizzas", pizzas_path %>

  <%= button_to "Destroy this pizza", @pizza, method: :delete %>
</div>